### ISSUE TITLE
UnboundLocalError: local variable 'f' referenced before assignment

### ISSUE THREAD

**Issue by Sabariessan** [f4rih/websploit#26]
Getting message 
UnboundLocalError: local variable 'f' referenced before assignment 
After running python2 websploit cmd

**Comment by jasmon93** [comment]
Also same with me

This is my error on termux


Traceback (most recent call last):
  File "websploit", line 55, in <module>
    from modules import arp_poisoner
  File "/data/data/com.termux/files/home/websploit/modules/arp_poisoner.py", line 11, in <module>
    from scapy.all import *
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/scapy/all.py", line 27, in <module>
    from scapy.route import *
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/scapy/route.py", line 203, in <module>
    conf.iface = get_working_if()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/scapy/arch/linux.py", line 144, in get_working_if
    for i in get_if_list():
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/scapy/arch/linux.py", line 127, in get_if_list
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment
$ python2 websploit
Traceback (most recent call last):
  File "websploit", line 55, in <module>
    from modules import arp_poisoner
  File "/data/data/com.termux/files/home/websploit/modules/arp_poisoner.py", line 11, in <module>
    from scapy.all import *
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/scapy/all.py", line 27, in <module>
    from scapy.route import *
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/scapy/route.py", line 203, in <module>
    conf.iface = get_working_if()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/scapy/arch/linux.py", line 144, in get_working_if
    for i in get_if_list():
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/scapy/arch/linux.py", line 127, in get_if_list
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment
$

**Comment by websploit** [comment]
new version released, check it out.

**Comment by jasmon93** [comment]
Can i use at termux? Sent from my Huawei phone-------- Original message --------From: Fardin Allahverdinazhand <notifications@github.com>Date: Mon, 20 Jan 2020, 21:58To: websploit/websploit <websploit@noreply.github.com>Cc: jasmon93 <jasmonkoko@gmail.com>, Comment <comment@noreply.github.com>Subject: Re: [websploit/websploit] UnboundLocalError: local variable 'f' referenced before assignment (#26)new version released, check it out.

**Comment by websploit** [comment]
> Can i use at termux? Sent from my Huawei phone-------- Original message --------From: Fardin Allahverdinazhand <notifications@github.com>Date: Mon, 20 Jan 2020, 21:58To: websploit/websploit <websploit@noreply.github.com>Cc: jasmon93 <jasmonkoko@gmail.com>, Comment <comment@noreply.github.com>Subject: Re: [websploit/websploit] UnboundLocalError: local variable 'f' referenced before assignment (#26)new version released, check it out. —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

in current version, websploit works with scapy only, other dependencies are removed, if you have scapy installed on your device websploit will work fine.

**Comment by jasmon93** [comment]
Hi. Still got same error in my termux.

Traceback (most recent call last):
  File
"/data/data/com.termux/files/usr/lib/python3.8/site-packages/scapy/arch/linux.py",
line 125, in get_if_list
    f = open("/proc/net/dev", "rb")
PermissionError: [Errno 13] Permission denied: '/proc/net/dev'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websploit.py", line 3, in <module>
    from core.utils import check_dependencies
  File "/data/data/com.termux/files/home/websploit/core/utils/__init__.py",
line 1, in <module>
    from .tools import *
  File "/data/data/com.termux/files/home/websploit/core/utils/tools.py",
line 1, in <module>
    from scapy.all import *
  File
"/data/data/com.termux/files/usr/lib/python3.8/site-packages/scapy/all.py",
line 27, in <module>
    from scapy.route import *
  File
"/data/data/com.termux/files/usr/lib/python3.8/site-packages/scapy/route.py",
line 203, in <module>
    conf.iface = get_working_if()
  File
"/data/data/com.termux/files/usr/lib/python3.8/site-packages/scapy/arch/linux.py",
line 144, in get_working_if
    for i in get_if_list():
  File
"/data/data/com.termux/files/usr/lib/python3.8/site-packages/scapy/arch/linux.py",
line 127, in get_if_list
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment
$
