### ISSUE TITLE
Module wifi_fap_spam is raising a FileNotFound Error

### ISSUE THREAD

**Issue by Nobody912** [f4rih/websploit#28]
I was testing the wifi_fap_spam module but got this error. wifi_fap works, but not spam.
Terminal Output:
`Traceback (most recent call last):
  File "/usr/local/bin/websploit", line 11, in <module>
    load_entry_point('websploit==4.0.3', 'console_scripts', 'websploit')()
  File "/usr/local/lib/python3.7/dist-packages/websploit-4.0.3-py3.7.egg/websploit/websploit.py", line 74, in start_wsf
    Main().cmdloop()
  File "/usr/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.7/dist-packages/websploit-4.0.3-py3.7.egg/websploit/websploit.py", line 35, in do_use
    module.cmdloop()
  File "/usr/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.7/dist-packages/websploit-4.0.3-py3.7.egg/websploit/modules/wifi_fap_spam.py", line 22, in do_execute
    name = get_fake_name()
  File "/usr/local/lib/python3.7/dist-packages/websploit-4.0.3-py3.7.egg/websploit/core/utils/tools.py", line 39, in get_fake_name
    with open(file_path) as file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/websploit-4.0.3-py3.7.egg/websploit/core/utils/fake_names'`

Thanks in advance.

**Comment by websploit** [comment]
Hi @Nobody912 
Thank you for reporting this bug, it's fixed in new patch.

**Comment by Dzima92** [comment]
FUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUCK

Отправлено из приложения "Почта" для Windows 10

От: Fardin Allahverdinazhand
Отправлено: 6 февраля 2020 г. в 9:30
Кому: websploit/websploit
Копия: Subscribed
Тема: Re: [websploit/websploit] Module wifi_fap_spam is raising aFileNotFound Error (#28)

Hi @Nobody912
Thank you for reporting this bug, it's fixed in new patch.

**Comment by 0xHuntEG** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/websploit", line 11, in <module>
    load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/websploit-4.0.4-py2.7.egg/websploit/websploit.py", line 34
    module.prompt = f"wsf > {line} > "
                                     ^
SyntaxError: invalid syntax

**Comment by shiv12340** [comment]
The Bug is fixed!
raceback (most recent call last):
  File "/usr/local/bin/websploit", line 11, in <module>
    load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2258, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/usr/local/lib/python2.7/dist-packages/websploit-4.0.4-py2.7.egg/websploit/websploit.py", line 34
    module.prompt = f"wsf > {line} > "
                                     ^
SyntaxError: invalid syntax

**Comment by Dzima92** [comment]
I like this app четверг, 06 февраля 2020г., 16:25 +02:00 от Дмитрий  dimacepelewa@gmail.com :

**Comment by 0x0ptim0us** [comment]
> The Bug is fixed!
> raceback (most recent call last):
> File "/usr/local/bin/websploit", line 11, in
> load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')()
> File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 565, in load_entry_point
> File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2598, in load_entry_point
> File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2258, in load
> File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2264, in resolve
> File "/usr/local/lib/python2.7/dist-packages/websploit-4.0.4-**py2.7**.egg/websploit/websploit.py", line 34
> module.prompt = f"wsf > {line} > "
> ^
> SyntaxError: invalid syntax

@shiv12340 
Please check your version of python , you are using python 2.7 !!!!

**Comment by websploit** [comment]
> Traceback (most recent call last):
> File "/usr/local/bin/websploit", line 11, in
> load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')()
> File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 489, in load_entry_point
> return get_distribution(dist).load_entry_point(group, name)
> File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2852, in load_entry_point
> return ep.load()
> File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2443, in load
> return self.resolve()
> File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2449, in resolve
> module = **import**(self.module_name, fromlist=['**name**'], level=0)
> File "/usr/local/lib/python2.7/dist-packages/websploit-4.0.4-py2.7.egg/websploit/websploit.py", line 34
> module.prompt = f"wsf > {line} > "
> ^
> SyntaxError: invalid syntax

Check your version of python !!!! websploit not support version 2.x anymore!
