### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by Abhiraj0812** [f4rih/websploit#32]
root@Devil:~# websploit
Traceback (most recent call last):
  File "/usr/local/bin/websploit", line 6, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2985, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 660, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 968, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 854, in resolve
pkg_resources.DistributionNotFound: The 'requests' distribution was not found and is required by websploit
root@Devil:~# 

![Screenshot 2020-03-31 01:12:40](https://user-images.githubusercontent.com/62891560/77922637-e89a4b00-72be-11ea-8b29-9157dc466eec.png)

**Comment by A-Unix** [comment]
root@kali:~# websploit
Traceback (most recent call last):
  File "/usr/local/bin/websploit", line 11, in <module>
    load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/websploit-4.0.4-py2.7.egg/websploit/websploit.py", line 34
    module.prompt = f"wsf > {line} > "
                                     ^
SyntaxError: invalid syntax
![errror](https://user-images.githubusercontent.com/54507991/79072055-957fb980-7cfc-11ea-93d2-ee30a42bd0c9.png)
What should i do?

**Comment by Abhiraj0812** [comment]
> root@kali:~# websploit
> Traceback (most recent call last):
> File "/usr/local/bin/websploit", line 11, in
> load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')()
> File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 489, in load_entry_point
> return get_distribution(dist).load_entry_point(group, name)
> File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2852, in load_entry_point
> return ep.load()
> File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2443, in load
> return self.resolve()
> File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2449, in resolve
> module = **import**(self.module_name, fromlist=['**name**'], level=0)
> File "/usr/local/lib/python2.7/dist-packages/websploit-4.0.4-py2.7.egg/websploit/websploit.py", line 34
> module.prompt = f"wsf > {line} > "
> ^
> SyntaxError: invalid syntax
> ![errror](https://user-images.githubusercontent.com/54507991/79072055-957fb980-7cfc-11ea-93d2-ee30a42bd0c9.png)
> What should i do?

make sure you have latest version, currently is 4.0.4.
git clone https://github.com/websploit/websploit.git
cd websploit
run setup :
python3 setup.py install
then open new terminal and type:
websploit
if there is issue let me know.
Thanks.
