### ISSUE TITLE
I want change port on web/pma

### ISSUE THREAD

**Issue by lv7777** [f4rih/websploit#4]
I want change port on web/pma, because my environment is using ssh tunnering that use port 60080.

I tried `set TARGET localhost:60080` but I getted error.

I tried to pma source on this repo,but  I don't read well python,so perhaps this error is not related this issue.

```

wsf:PMA > run
[*] Your Target : localhost:60080
[*]Loading Path List ... Please Wait ...
Traceback (most recent call last):
  File "/usr/bin/websploit", line 160, in <module>
    start()
  File "/usr/bin/websploit", line 158, in start
    main()
  File "/usr/bin/websploit", line 132, in main
    main()
  File "/usr/bin/websploit", line 95, in main
    phpmyadmin.phpmyadmin()
  File "/usr/share/websploit/modules/phpmyadmin.py", line 31, in phpmyadmin
    phpmyadmin()
  File "/usr/share/websploit/modules/phpmyadmin.py", line 24, in phpmyadmin
    phpmyadmin()
  File "/usr/share/websploit/modules/phpmyadmin.py", line 136, in phpmyadmin
    res = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

```

can I change using port?

**Comment by RedToor** [comment]
U can't set port, but u can edict the module file https://github.com/websploit/websploit/blob/master/modules/phpmyadmin.py#L134 adding the port `conn = httplib.HTTPConnection(options[0],60080)`

**Comment by lv7777** [comment]
thanks!
