### ISSUE TITLE
KeyError: 'green'

### ISSUE THREAD

**Issue by GarrickLin** [f4rih/websploit#42]
What's the problem ?
```
λ websploit

    ____    __    ____
    \   \  /  \  /   /     |    Welcome to Websploit
     \   \/    \/   /      |    Version : 4.0.4
      \            /       |    https://github.com/websploit/websploit
       \    /\    /        |    Author : Fardin Allahverdinazhand
        \__/  \__/         |    Codename : Reborn



wsf > show
Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\Scripts\websploit-script.py", line 11, in <module>
    load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')()
  File "D:\ProgramData\Miniconda3\lib\site-packages\websploit-4.0.4-py3.7.egg\websploit\websploit.py", line 74, in start_wsf
    Main().cmdloop()
  File "D:\ProgramData\Miniconda3\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "D:\ProgramData\Miniconda3\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "D:\ProgramData\Miniconda3\lib\site-packages\websploit-4.0.4-py3.7.egg\websploit\websploit.py", line 44, in do_show
    all_modules()
  File "D:\ProgramData\Miniconda3\lib\site-packages\websploit-4.0.4-py3.7.egg\websploit\modules\__init__.py", line 11, in all_modules
    cp.green(f"{'Modules':<20}\t{'Description':<20}")
  File "D:\ProgramData\Miniconda3\lib\site-packages\websploit-4.0.4-py3.7.egg\websploit\core\utils\output.py", line 65, in green
    self._output(text=text, status="green")
  File "D:\ProgramData\Miniconda3\lib\site-packages\websploit-4.0.4-py3.7.egg\websploit\core\utils\output.py", line 45, in _output
    print(f"{symbols[status]} {text}")
KeyError: 'green'
```

**Comment by websploit** [comment]
@GarrickLin 
Hello.
Websploit doesn't support windows .

**Comment by misbagas** [comment]
hey @websploit 

are websploit is compatible on macos

**Comment by Taciones** [comment]
Looks good : 
![image](https://user-images.githubusercontent.com/45239959/232155036-8834b594-600f-4b03-92d4-1ddc6d96278f.png)
