### ISSUE TITLE
Android 10

### ISSUE THREAD

**Issue by Hoccond** [f4rih/websploit#46]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/scapy-2.4.3-py3.8.egg/scapy/arch/linux.py", line 125, in get_if_list
    f = open("/proc/net/dev", "rb")
PermissionError: [Errno 13] Permission denied: '/proc/net/dev'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/websploit", line 11, in <module>
    load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/websploit-4.0.4-py3.8.egg/websploit/websploit.py", line 3, in <module>
    from .core.utils import check_dependencies
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/websploit-4.0.4-py3.8.egg/websploit/core/utils/__init__.py", line 1, in <module>
    from .tools import *
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/websploit-4.0.4-py3.8.egg/websploit/core/utils/tools.py", line 1, in <module>
    from scapy.all import *
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/scapy-2.4.3-py3.8.egg/scapy/all.py", line 27, in <module>
    from scapy.route import *
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/scapy-2.4.3-py3.8.egg/scapy/route.py", line 203, in <module>
    conf.iface = get_working_if()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/scapy-2.4.3-py3.8.egg/scapy/arch/linux.py", line 144, in get_working_if
    for i in get_if_list():
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/scapy-2.4.3-py3.8.egg/scapy/arch/linux.py", line 127, in get_if_list
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment

**Comment by FuhadIhthisham** [comment]
I'm also facing the same issue..Anyone fix it !!!

**Comment by LavSarkari** [comment]
Yaa same with me...

**Comment by alvarob33** [comment]
Make sure you have done with all permissions, typing “su” before of running the tool.

**Comment by kahogedeon** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/websploit", line 33, in <module>

**Comment by gmiwoj** [comment]
got it to work on my andy10

![10a](https://user-images.githubusercontent.com/36712913/104735529-f9c72200-5741-11eb-97fc-f104d8469fc2.jpg)



i installed it just as shown in this guide:
https://www.youtube.com/watch?v=4Pmecwv9CJE

except in (2:43) had to add sudo for setup to complete without permission errors:
`sudo python setup.py install`

and i also launch websploit with sudo just in case, don't know if that does anything :
`sudo websploit`

mind that this launches from a "/bin/websploit" file, not from websploit.py file in your current folder. 

also before doing all this delete clean all websploit files and folders left from previous attempts, including /bin/websploit file.

also also, the correct git to clone is this git right here :
`git clone https://github.com/websploit/websploit`

and NOT from https://github.com/The404Hacking/websploit.git
that one is over 7 years old and doesn't seem to work anymore.
