### ISSUE TITLE
arp_spoof execute has exception

### ISSUE THREAD

**Issue by ImanX** [f4rih/websploit#48]
I installed websploit and I'm facing issue in arp_spoof>execute
```
Traceback (most recent call last):
  File "/usr/local/bin/websploit", line 11, in <module>
    load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')()
  File "/usr/local/lib/python3.8/site-packages/websploit-4.0.4-py3.8.egg/websploit/websploit.py", line 74, in start_wsf
    Main().cmdloop()
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.8/site-packages/websploit-4.0.4-py3.8.egg/websploit/websploit.py", line 35, in do_use
    module.cmdloop()
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.8/site-packages/websploit-4.0.4-py3.8.egg/websploit/modules/arp_spoof.py", line 24, in do_execute
    self._spoof(target=self.parameters['target'], getway=self.parameters['gateway'])
  File "/usr/local/lib/python3.8/site-packages/websploit-4.0.4-py3.8.egg/websploit/modules/arp_spoof.py", line 37, in _spoof
    target_mac = get_mac(ip=target)
  File "/usr/local/lib/python3.8/site-packages/websploit-4.0.4-py3.8.egg/websploit/core/utils/tools.py", line 7, in get_mac
    ans, _ = srp(Ether(dst='ff:ff:ff:ff:ff:ff')/ARP(pdst=ip), timeout=3, verbose=0)
  File "/usr/local/lib/python3.8/site-packages/scapy-2.4.3-py3.8.egg/scapy/sendrecv.py", line 503, in srp
    s = conf.L2socket(promisc=promisc, iface=iface,
  File "/usr/local/lib/python3.8/site-packages/scapy-2.4.3-py3.8.egg/scapy/arch/bpf/supersocket.py", line 234, in __init__
    super(L2bpfListenSocket, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/scapy-2.4.3-py3.8.egg/scapy/arch/bpf/supersocket.py", line 57, in __init__
    (self.ins, self.dev_bpf) = get_dev_bpf()
  File "/usr/local/lib/python3.8/site-packages/scapy-2.4.3-py3.8.egg/scapy/arch/bpf/core.py", line 115, in get_dev_bpf
    raise Scapy_Exception("No /dev/bpf handle is available !")
scapy.error.Scapy_Exception: No /dev/bpf handle is available !
Exception ignored in: <function _L2bpfSocket.__del__ at 0x10272c5e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/scapy-2.4.3-py3.8.egg/scapy/arch/bpf/supersocket.py", line 131, in __del__
    self.close()
  File "/usr/local/lib/python3.8/site-packages/scapy-2.4.3-py3.8.egg/scapy/arch/bpf/supersocket.py", line 203, in close
    if not self.closed and self.ins is not None:
AttributeError: 'L2bpfSocket' object has no attribute 'ins'


```

**Comment by ImanX** [comment]
OK! I ran `websploit` by `sudo` and it's OK
