### ISSUE TITLE
wifi_fap_spam error

### ISSUE THREAD

**Issue by jgx0** [f4rih/websploit#57]
i got this error using wifi_fap_spam as root

`Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/websploit-4.0.4-py3.6.egg/websploit/modules/wifi_fap_spam.py", line 48, in __init__
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/websploit-4.0.4-py3.6.egg/websploit/modules/wifi_fap_spam.py", line 64, in run
    sendp(frame, inter=0.1, iface=self.iface, loop=1)
  File "/usr/local/lib/python3.6/dist-packages/scapy-2.4.4-py3.6.egg/scapy/sendrecv.py", line 376, in sendp
    socket = socket or conf.L2socket(iface=iface, *args, **kargs)
  File "/usr/local/lib/python3.6/dist-packages/scapy-2.4.4-py3.6.egg/scapy/arch/linux.py", line 398, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/usr/lib/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted`

**Comment by adnan007d** [comment]
Try running as root

**Comment by jgx0** [comment]
k ill try
