### ISSUE TITLE
Start websploit / Error : FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

### ISSUE THREAD

**Issue by izaletr** [f4rih/websploit#65]
File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'
Kali 2020.4

**Comment by teyhoo** [comment]
I have this Problem too

**Comment by BinaryHijacke** [comment]
how fix it

**Comment by websploit** [comment]
Checkout this answer : 
https://github.com/websploit/websploit/issues/66#issuecomment-751438370

**Comment by Hyrkania** [comment]
I had the same issue as @izaletr had!

After run command:
> $ websploit

I get this error:
```
Traceback (most recent call last):
  File "/usr/bin/websploit", line 11, in <module>
    load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 473, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/websploit/websploit.py", line 3, in <module>
    from .core.utils import check_dependencies
  File "/usr/lib/python3/dist-packages/websploit/core/utils/__init__.py", line 1, in <module>
    from .tools import *
  File "/usr/lib/python3/dist-packages/websploit/core/utils/tools.py", line 1, in <module>
    from scapy.all import *
  File "/usr/lib/python3/dist-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/lib/python3/dist-packages/scapy/arch/__init__.py", line 27, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/lib/python3/dist-packages/scapy/arch/bpf/core.py", line 30, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.9/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'
```

**### Solution:**

You just need to go to this directory:

> $ cd /usr/lib/x86_64-linux-gnu/

and make a symlink to libc.a with this link (liblibc.a):

> $ ln -s -f libc.a liblibc.a

Hope this work for you too.:blush::blush:

**Comment by gzsrdfhxrsd** [comment]
it didn't work for me

```
└─$ $ cd /usr/lib/x86_64-linux-gnu/

cd: No such file or directory: / usr / lib / x86_64-linux-gnu
```
