### ISSUE TITLE
[ERRNO 13] permission denied

### ISSUE THREAD

**Issue by AnsariMasoom** [f4rih/websploit#72]
when I try to open websploit in termux ( when i give command $websploit it says permission denied at the end) . Please hellp me
$ websploit
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/websploit", line 33, in <module>
    sys.exit(load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')())
  File "/data/data/com.termux/files/usr/bin/websploit", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/data/data/com.termux/files/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/data/data/com.termux/files/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/websploit-4.0.4-py3.9.egg/websploit/websploit.py", line 3, in <module>
    from .core.utils import check_dependencies
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/websploit-4.0.4-py3.9.egg/websploit/core/utils/__init__.py", line 1, in <module>
    from .tools import *
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/websploit-4.0.4-py3.9.egg/websploit/core/utils/tools.py", line 1, in <module>
    from scapy.all import *
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/scapy-2.4.5-py3.9.egg/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/scapy-2.4.5-py3.9.egg/scapy/arch/__init__.py", line 135, in <module>
    _set_conf_sockets()  # Apply config
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/scapy-2.4.5-py3.9.egg/scapy/config.py", line 618, in _set_conf_sockets
    conf.ifaces.reload()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/scapy-2.4.5-py3.9.egg/scapy/interfaces.py", line 238, in reload
    self._reload_provs()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/scapy-2.4.5-py3.9.egg/scapy/interfaces.py", line 234, in _reload_provs
    self._load(prov.reload(), prov)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/scapy-2.4.5-py3.9.egg/scapy/interfaces.py", line 53, in reload
    return self.load()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/scapy-2.4.5-py3.9.egg/scapy/arch/linux.py", line 420, in load
    get_if_raw_hwaddr(i, siocgifhwaddr=SIOCGIFHWADDR)[1]
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/scapy-2.4.5-py3.9.egg/scapy/arch/common.py", line 87, in get_if_raw_hwaddr
    get_if(iff, siocgifhwaddr)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/scapy-2.4.5-py3.9.egg/scapy/arch/common.py", line 65, in get_if
    return ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
PermissionError: [Errno 13] Permission denied
$

**Comment by aimgo** [comment]
use `sudo websploit` .

**Comment by 88JC** [comment]
> use `sudo websploit` .

Tetap tidak bisa

**Comment by aimgo** [comment]
apakah kamu punya root?
