### ISSUE TITLE
(Error13) permission denied

### ISSUE THREAD

**Issue by AnonymousUser0911** [f4rih/websploit#78]
wsf > arp_spoof > execute
Traceback (most recent call last):
  File "/usr/local/bin/websploit", line 33, in <module>
    sys.exit(load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')())
  File "/usr/local/lib/python3.9/dist-packages/websploit-4.0.4-py3.9.egg/websploit/websploit.py", line 74, in start_wsf
    Main().cmdloop()
  File "/usr/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.9/dist-packages/websploit-4.0.4-py3.9.egg/websploit/websploit.py", line 35, in do_use
    module.cmdloop()
  File "/usr/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.9/dist-packages/websploit-4.0.4-py3.9.egg/websploit/modules/arp_spoof.py", line 24, in do_execute
    self._spoof(target=self.parameters['target'], getway=self.parameters['gateway'])
  File "/usr/local/lib/python3.9/dist-packages/websploit-4.0.4-py3.9.egg/websploit/modules/arp_spoof.py", line 37, in _spoof
    target_mac = get_mac(ip=target)
  File "/usr/local/lib/python3.9/dist-packages/websploit-4.0.4-py3.9.egg/websploit/core/utils/tools.py", line 7, in get_mac
    ans, _ = srp(Ether(dst='ff:ff:ff:ff:ff:ff')/ARP(pdst=ip), timeout=3, verbose=0)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 552, in srp
    s = conf.L2socket(promisc=promisc, iface=iface,
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 398, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied
I got this error ,how to solve it
Please solve it

**Comment by f4rih** [comment]
Hi, run Websploit as root

**Comment by AnonymousUser0911** [comment]
Yes , I too tried that but still showing this error

**Comment by ghost** [comment]
use command `uname -a` and tell me what does it outputs

**Comment by AnonymousUser0911** [comment]
┌──(kali㉿localhost)-[~]
└─$ uname -a
Linux localhost 4.9.117+ #2 SMP PREEMPT Tue Jan 18 23:49:31 CST 2022
aarch64 GNU/Linux

┌──(kali㉿localhost)-[~]
└─$
I got this error message
